conda_environment: "workflow/envs/nextstrain.yaml"

genesforglycosylation: ["G", "F"]

buildstorun: ["genome", "G", "F"]

description: "config/description.md"

strain_id_field: "accession"
display_strain_field: "strain_original"

subtypes: ['a', 'b']

filter:
  group_by: "year country"
  min_length:
    genome: 10000
    G: 600
    F: 600
  subsample_max_sequences:
    genome: 2000
    G: 4000
    F: 4000

files:
  color_schemes: "config/colors.tsv"
  auspice_config: "config/auspice_config.json"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "country"