conda_environment: "workflow/envs/nextstrain.yaml"

genesforglycosylation: ["G", "F"]

buildstorun: ["genome", "G", "F"]
#buildstorun: ["genome"]

exclude: "config/outliers.txt"

description: "config/description.md"

strain_id_field: "accession"
display_strain_field: "strain"

subtypes: ['a', 'b']

filter:
  group_by: "year country division"
  min_coverage:
    genome: 0.3
    G: 0.3
    F: 0.3

  subsample_max_sequences:
    genome: 2000
    G: 3000
    F: 3000
    
subsampling:
  state: --query "division == 'Washington'" --subsample-max-sequences 500 
  # "min_coverage = lambda w: f'{w.build_name}_coverage > 0.3'"
  country: --query "division != 'Washington'" "{w.build_name}_coverage > 0.3" --subsample-max-sequences 200
   #country: --query "division != 'Washington'" "min_coverage = lambda w: f'{w.build_name}_coverage > 0.3'" --subsample-max-sequences 200
  #country: --query "min_coverage = lambda w: f'{w.build_name}_coverage<{config["filter"]["min_coverage"].get(w.build_name, 0.3)}"  --subsample-max-sequences 200
  # "min_coverage = lambda w: f'{w.build_name}_coverage<{config["filter"]["min_coverage"].get(w.build_name, 0.3)}'"

files:
  color_schemes: "config/colors.tsv"
  auspice_config: "config/auspice_config.json"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "country"